[tool.poetry]
name = "tfip"
version = "0.1.0"
description = ""
authors = ["Kirill Kondrenko <kondrenkokp@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
networkx = "^3.2.1"
matplotlib = "^3.8.3"
mpld3 = "^0.5.10"
scipy = "^1.12.0"
mypy = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
