ARTICLE_SELECTOR = "article"
ARTICLE_MAIN_TITLE = ".tm-title_h1"
LIST_ARTICLE_MAIN_TITLE = ".tm-title__link"
ARTICLE_BODY = ".tm-article-body"
ARTICLE_TIMESTAMP = ".tm-article-datetime-published time"
