habr_article_selector = "article"
habr_article_main_title = ".tm-title_h1"
list_habr_article_main_title = ".tm-title__link"
habr_article_body = ".tm-article-body"
habr_article_timestamp = ".tm-article-datetime-published time"
link_tag = "a"
